version: '3.1'

services:
  ioiprint:
    build:
      context: .
      args:
        TIMEZONE: Asia/Tehran  # The timezone in which times are calculated
    ports:
    - 5000:5000  # The first 5000 is the port the print service will be on
    volumes:
    - ./uploads/:/usr/src/ioiprint/uploads/  # the directory before ":" is the uploads directory on the host machine
    environment:
      NETADMIN_URL: netadmin.ioi2017.org  # the address of IOI Net Administration System
      UPLOADS_DIRECTORY: /usr/src/ioiprint/uploads/
      CUPS_ADDRESS: cups-back:631
      # The printer or class names used for contest zones in json format (They should exist in cups-back server)
      PRINTERS_FOR_ZONES: >
        {
          "A": "floor1",
          "B": "floor1",
          "C": "floor1",
          "D": "floor1",
          "E": "floor2",
          "F": "floor2",
          "G": "floor2",
          "H": "floor2"
        }
      DEFAULT_PRINTER: default  # The printer or class name used for translation and mass requests

  cups-front:
    build:
      context: cups/
      args:
        PRINTER_NAME: ioi_printer  # The printer name to setup on contestants' computers
    ports:
    - 631:631
    environment:
      # Username and password used for cups-front server
      CUPS_USER_ADMIN: admin
      CUPS_USER_PASSWORD: 123456
      PRINTER_NAME: ioi_printer  # It should be the same as PRINTER_NAME in build args

  cups-back:
    image: aadl/cups-alpine:2.2.3
    ports:
    - 6631:631
    environment:
      # Username and password used for cups-back server
      CUPS_USER_ADMIN: admin
      CUPS_USER_PASSWORD: 123456
